//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialGamePublicAPI.SocialGameBLLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HumourStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] InterestsIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FacebookProfile {
            get {
                return this.FacebookProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookProfileField, value) != true)) {
                    this.FacebookProfileField = value;
                    this.RaisePropertyChanged("FacebookProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HumourStatusId {
            get {
                return this.HumourStatusIdField;
            }
            set {
                if ((this.HumourStatusIdField.Equals(value) != true)) {
                    this.HumourStatusIdField = value;
                    this.RaisePropertyChanged("HumourStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] InterestsIDs {
            get {
                return this.InterestsIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestsIDsField, value) != true)) {
                    this.InterestsIDsField = value;
                    this.RaisePropertyChanged("InterestsIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LinkedInProfile {
            get {
                return this.LinkedInProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInProfileField, value) != true)) {
                    this.LinkedInProfileField = value;
                    this.RaisePropertyChanged("LinkedInProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationshipTag", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class RelationshipTag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Graph", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class Graph : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGamePublicAPI.SocialGameBLLService.HumourStatus[] HumourStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGamePublicAPI.SocialGameBLLService.Interest[] InterestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[] RelationshipTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGamePublicAPI.SocialGameBLLService.Relationship[] RelationshipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGamePublicAPI.SocialGameBLLService.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialGamePublicAPI.SocialGameBLLService.HumourStatus[] HumourStatus {
            get {
                return this.HumourStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HumourStatusField, value) != true)) {
                    this.HumourStatusField = value;
                    this.RaisePropertyChanged("HumourStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialGamePublicAPI.SocialGameBLLService.Interest[] Interests {
            get {
                return this.InterestsField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestsField, value) != true)) {
                    this.InterestsField = value;
                    this.RaisePropertyChanged("Interests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[] RelationshipTags {
            get {
                return this.RelationshipTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipTagsField, value) != true)) {
                    this.RelationshipTagsField = value;
                    this.RaisePropertyChanged("RelationshipTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialGamePublicAPI.SocialGameBLLService.Relationship[] Relationships {
            get {
                return this.RelationshipsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipsField, value) != true)) {
                    this.RelationshipsField = value;
                    this.RaisePropertyChanged("Relationships");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SocialGamePublicAPI.SocialGameBLLService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumourStatus", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class HumourStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Interest", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class Interest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relationship", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class Relationship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelationshipTagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserBEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelationshipTagId {
            get {
                return this.RelationshipTagIdField;
            }
            set {
                if ((this.RelationshipTagIdField.Equals(value) != true)) {
                    this.RelationshipTagIdField = value;
                    this.RaisePropertyChanged("RelationshipTagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((this.StrengthField.Equals(value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserAEmail {
            get {
                return this.UserAEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAEmailField, value) != true)) {
                    this.UserAEmailField = value;
                    this.RaisePropertyChanged("UserAEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserBEmail {
            get {
                return this.UserBEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBEmailField, value) != true)) {
                    this.UserBEmailField = value;
                    this.RaisePropertyChanged("UserBEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationshipRequest", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    public partial class RelationshipRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelationshipTagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RelationshipTagId {
            get {
                return this.RelationshipTagIdField;
            }
            set {
                if ((this.RelationshipTagIdField.Equals(value) != true)) {
                    this.RelationshipTagIdField = value;
                    this.RaisePropertyChanged("RelationshipTagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestedEmail {
            get {
                return this.RequestedEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedEmailField, value) != true)) {
                    this.RequestedEmailField = value;
                    this.RaisePropertyChanged("RequestedEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequesterEmail {
            get {
                return this.RequesterEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterEmailField, value) != true)) {
                    this.RequesterEmailField = value;
                    this.RaisePropertyChanged("RequesterEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((this.StrengthField.Equals(value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialGameBLLService.ISocialGameBLLService")]
    public interface ISocialGameBLLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetData", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetData", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContractResponse")]
        SocialGamePublicAPI.SocialGameBLLService.CompositeType GetDataUsingDataContract(SocialGamePublicAPI.SocialGameBLLService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.CompositeType> GetDataUsingDataContractAsync(SocialGamePublicAPI.SocialGameBLLService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RegisterUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RegisterUserResponse")]
        SocialGamePublicAPI.SocialGameBLLService.User RegisterUser(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RegisterUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RegisterUserResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> RegisterUserAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/LoginUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/LoginUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/ISocialGameBLLService/LoginUserFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        SocialGamePublicAPI.SocialGameBLLService.User LoginUser(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/LoginUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/LoginUserResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> LoginUserAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/UpdateUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/UpdateUserResponse")]
        SocialGamePublicAPI.SocialGameBLLService.User UpdateUser(SocialGamePublicAPI.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/UpdateUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/UpdateUserResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> UpdateUserAsync(SocialGamePublicAPI.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTags", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagsResponse")]
        SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[] GetRelationshipTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTags", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagsResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[]> GetRelationshipTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationships", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsResponse")]
        SocialGamePublicAPI.SocialGameBLLService.Graph GetRelationships(SocialGamePublicAPI.SocialGameBLLService.User User, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationships", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.Graph> GetRelationshipsAsync(SocialGamePublicAPI.SocialGameBLLService.User User, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequestResponse")]
        SocialGamePublicAPI.SocialGameBLLService.RelationshipRequest MakeRelationshipRequest(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Other, int RelationshipTagId, int Strength);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequestResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.RelationshipRequest> MakeRelationshipRequestAsync(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Other, int RelationshipTagId, int Strength);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetShortestPath", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetShortestPathResponse")]
        SocialGamePublicAPI.SocialGameBLLService.User[] GetShortestPath(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Goal, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetShortestPath", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetShortestPathResponse")]
        System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User[]> GetShortestPathAsync(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Goal, int Depth);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISocialGameBLLServiceChannel : SocialGamePublicAPI.SocialGameBLLService.ISocialGameBLLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SocialGameBLLServiceClient : System.ServiceModel.ClientBase<SocialGamePublicAPI.SocialGameBLLService.ISocialGameBLLService>, SocialGamePublicAPI.SocialGameBLLService.ISocialGameBLLService {
        
        public SocialGameBLLServiceClient() {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialGameBLLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.CompositeType GetDataUsingDataContract(SocialGamePublicAPI.SocialGameBLLService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.CompositeType> GetDataUsingDataContractAsync(SocialGamePublicAPI.SocialGameBLLService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.User RegisterUser(string Email, string Password) {
            return base.Channel.RegisterUser(Email, Password);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> RegisterUserAsync(string Email, string Password) {
            return base.Channel.RegisterUserAsync(Email, Password);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.User LoginUser(string Email, string Password) {
            return base.Channel.LoginUser(Email, Password);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> LoginUserAsync(string Email, string Password) {
            return base.Channel.LoginUserAsync(Email, Password);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.User UpdateUser(SocialGamePublicAPI.SocialGameBLLService.User User) {
            return base.Channel.UpdateUser(User);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User> UpdateUserAsync(SocialGamePublicAPI.SocialGameBLLService.User User) {
            return base.Channel.UpdateUserAsync(User);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[] GetRelationshipTags() {
            return base.Channel.GetRelationshipTags();
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.RelationshipTag[]> GetRelationshipTagsAsync() {
            return base.Channel.GetRelationshipTagsAsync();
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.Graph GetRelationships(SocialGamePublicAPI.SocialGameBLLService.User User, int Depth) {
            return base.Channel.GetRelationships(User, Depth);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.Graph> GetRelationshipsAsync(SocialGamePublicAPI.SocialGameBLLService.User User, int Depth) {
            return base.Channel.GetRelationshipsAsync(User, Depth);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.RelationshipRequest MakeRelationshipRequest(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Other, int RelationshipTagId, int Strength) {
            return base.Channel.MakeRelationshipRequest(Me, Other, RelationshipTagId, Strength);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.RelationshipRequest> MakeRelationshipRequestAsync(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Other, int RelationshipTagId, int Strength) {
            return base.Channel.MakeRelationshipRequestAsync(Me, Other, RelationshipTagId, Strength);
        }
        
        public SocialGamePublicAPI.SocialGameBLLService.User[] GetShortestPath(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Goal, int Depth) {
            return base.Channel.GetShortestPath(Me, Goal, Depth);
        }
        
        public System.Threading.Tasks.Task<SocialGamePublicAPI.SocialGameBLLService.User[]> GetShortestPathAsync(SocialGamePublicAPI.SocialGameBLLService.User Me, SocialGamePublicAPI.SocialGameBLLService.User Goal, int Depth) {
            return base.Channel.GetShortestPathAsync(Me, Goal, Depth);
        }
    }
}
