/* soapH.h
   Generated by gSOAP 2.8.17 from stub/Service1.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_byte(soap, data),0) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_int(soap, data),0) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_std__string(soap, data),0) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__UserTagContract
#define SOAP_TYPE_ns3__UserTagContract (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__UserTagContract(struct soap*, const char*, int, const ns3__UserTagContract *, const char*);
SOAP_FMAC3 ns3__UserTagContract * SOAP_FMAC4 soap_in_ns3__UserTagContract(struct soap*, const char*, ns3__UserTagContract *, const char*);

#ifndef soap_write_ns3__UserTagContract
#define soap_write_ns3__UserTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:UserTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__UserTagContract * SOAP_FMAC4 soap_get_ns3__UserTagContract(struct soap*, ns3__UserTagContract *, const char*, const char*);

#ifndef soap_read_ns3__UserTagContract
#define soap_read_ns3__UserTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__UserTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__UserTagContract * SOAP_FMAC2 soap_instantiate_ns3__UserTagContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__UserTagContract * soap_new_ns3__UserTagContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__UserTagContract(soap, n, NULL, NULL, NULL); }

inline ns3__UserTagContract * soap_new_req_ns3__UserTagContract(struct soap *soap) { ns3__UserTagContract *_p = soap_instantiate_ns3__UserTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__UserTagContract * soap_new_set_ns3__UserTagContract(struct soap *soap, int *Id, std::string *UserTagName) { ns3__UserTagContract *_p = soap_instantiate_ns3__UserTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__UserTagContract::Id = Id; _p->ns3__UserTagContract::UserTagName = UserTagName; } return _p; }

inline void soap_delete_ns3__UserTagContract(struct soap *soap, ns3__UserTagContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__UserTagContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ArrayOfUserTagContract
#define SOAP_TYPE_ns3__ArrayOfUserTagContract (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ArrayOfUserTagContract(struct soap*, const char*, int, const ns3__ArrayOfUserTagContract *, const char*);
SOAP_FMAC3 ns3__ArrayOfUserTagContract * SOAP_FMAC4 soap_in_ns3__ArrayOfUserTagContract(struct soap*, const char*, ns3__ArrayOfUserTagContract *, const char*);

#ifndef soap_write_ns3__ArrayOfUserTagContract
#define soap_write_ns3__ArrayOfUserTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:ArrayOfUserTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ArrayOfUserTagContract * SOAP_FMAC4 soap_get_ns3__ArrayOfUserTagContract(struct soap*, ns3__ArrayOfUserTagContract *, const char*, const char*);

#ifndef soap_read_ns3__ArrayOfUserTagContract
#define soap_read_ns3__ArrayOfUserTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ArrayOfUserTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__ArrayOfUserTagContract * SOAP_FMAC2 soap_instantiate_ns3__ArrayOfUserTagContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__ArrayOfUserTagContract * soap_new_ns3__ArrayOfUserTagContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__ArrayOfUserTagContract(soap, n, NULL, NULL, NULL); }

inline ns3__ArrayOfUserTagContract * soap_new_req_ns3__ArrayOfUserTagContract(struct soap *soap) { ns3__ArrayOfUserTagContract *_p = soap_instantiate_ns3__ArrayOfUserTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__ArrayOfUserTagContract * soap_new_set_ns3__ArrayOfUserTagContract(struct soap *soap, std::vector<ns3__UserTagContract * >& UserTagContract) { ns3__ArrayOfUserTagContract *_p = soap_instantiate_ns3__ArrayOfUserTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__ArrayOfUserTagContract::UserTagContract = UserTagContract; } return _p; }

inline void soap_delete_ns3__ArrayOfUserTagContract(struct soap *soap, ns3__ArrayOfUserTagContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ArrayOfUserTagContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__HumorContract
#define SOAP_TYPE_ns3__HumorContract (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__HumorContract(struct soap*, const char*, int, const ns3__HumorContract *, const char*);
SOAP_FMAC3 ns3__HumorContract * SOAP_FMAC4 soap_in_ns3__HumorContract(struct soap*, const char*, ns3__HumorContract *, const char*);

#ifndef soap_write_ns3__HumorContract
#define soap_write_ns3__HumorContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:HumorContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__HumorContract * SOAP_FMAC4 soap_get_ns3__HumorContract(struct soap*, ns3__HumorContract *, const char*, const char*);

#ifndef soap_read_ns3__HumorContract
#define soap_read_ns3__HumorContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__HumorContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__HumorContract * SOAP_FMAC2 soap_instantiate_ns3__HumorContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__HumorContract * soap_new_ns3__HumorContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__HumorContract(soap, n, NULL, NULL, NULL); }

inline ns3__HumorContract * soap_new_req_ns3__HumorContract(struct soap *soap) { ns3__HumorContract *_p = soap_instantiate_ns3__HumorContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__HumorContract * soap_new_set_ns3__HumorContract(struct soap *soap, std::string *HumorName, int *Id) { ns3__HumorContract *_p = soap_instantiate_ns3__HumorContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__HumorContract::HumorName = HumorName; _p->ns3__HumorContract::Id = Id; } return _p; }

inline void soap_delete_ns3__HumorContract(struct soap *soap, ns3__HumorContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__HumorContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ConnectionTagContract
#define SOAP_TYPE_ns3__ConnectionTagContract (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ConnectionTagContract(struct soap*, const char*, int, const ns3__ConnectionTagContract *, const char*);
SOAP_FMAC3 ns3__ConnectionTagContract * SOAP_FMAC4 soap_in_ns3__ConnectionTagContract(struct soap*, const char*, ns3__ConnectionTagContract *, const char*);

#ifndef soap_write_ns3__ConnectionTagContract
#define soap_write_ns3__ConnectionTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:ConnectionTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ConnectionTagContract * SOAP_FMAC4 soap_get_ns3__ConnectionTagContract(struct soap*, ns3__ConnectionTagContract *, const char*, const char*);

#ifndef soap_read_ns3__ConnectionTagContract
#define soap_read_ns3__ConnectionTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ConnectionTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__ConnectionTagContract * SOAP_FMAC2 soap_instantiate_ns3__ConnectionTagContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__ConnectionTagContract * soap_new_ns3__ConnectionTagContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__ConnectionTagContract(soap, n, NULL, NULL, NULL); }

inline ns3__ConnectionTagContract * soap_new_req_ns3__ConnectionTagContract(struct soap *soap) { ns3__ConnectionTagContract *_p = soap_instantiate_ns3__ConnectionTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__ConnectionTagContract * soap_new_set_ns3__ConnectionTagContract(struct soap *soap, std::string *ConnectionTagName, int *Id) { ns3__ConnectionTagContract *_p = soap_instantiate_ns3__ConnectionTagContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__ConnectionTagContract::ConnectionTagName = ConnectionTagName; _p->ns3__ConnectionTagContract::Id = Id; } return _p; }

inline void soap_delete_ns3__ConnectionTagContract(struct soap *soap, ns3__ConnectionTagContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ConnectionTagContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ConnectionContract
#define SOAP_TYPE_ns3__ConnectionContract (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ConnectionContract(struct soap*, const char*, int, const ns3__ConnectionContract *, const char*);
SOAP_FMAC3 ns3__ConnectionContract * SOAP_FMAC4 soap_in_ns3__ConnectionContract(struct soap*, const char*, ns3__ConnectionContract *, const char*);

#ifndef soap_write_ns3__ConnectionContract
#define soap_write_ns3__ConnectionContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:ConnectionContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ConnectionContract * SOAP_FMAC4 soap_get_ns3__ConnectionContract(struct soap*, ns3__ConnectionContract *, const char*, const char*);

#ifndef soap_read_ns3__ConnectionContract
#define soap_read_ns3__ConnectionContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ConnectionContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__ConnectionContract * SOAP_FMAC2 soap_instantiate_ns3__ConnectionContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__ConnectionContract * soap_new_ns3__ConnectionContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__ConnectionContract(soap, n, NULL, NULL, NULL); }

inline ns3__ConnectionContract * soap_new_req_ns3__ConnectionContract(struct soap *soap) { ns3__ConnectionContract *_p = soap_instantiate_ns3__ConnectionContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__ConnectionContract * soap_new_set_ns3__ConnectionContract(struct soap *soap, ns3__ConnectionTagContract *ConnectionTag, int *Id, int *Strength, ns3__UserContract *User) { ns3__ConnectionContract *_p = soap_instantiate_ns3__ConnectionContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__ConnectionContract::ConnectionTag = ConnectionTag; _p->ns3__ConnectionContract::Id = Id; _p->ns3__ConnectionContract::Strength = Strength; _p->ns3__ConnectionContract::User = User; } return _p; }

inline void soap_delete_ns3__ConnectionContract(struct soap *soap, ns3__ConnectionContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ConnectionContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__ArrayOfConnectionContract
#define SOAP_TYPE_ns3__ArrayOfConnectionContract (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__ArrayOfConnectionContract(struct soap*, const char*, int, const ns3__ArrayOfConnectionContract *, const char*);
SOAP_FMAC3 ns3__ArrayOfConnectionContract * SOAP_FMAC4 soap_in_ns3__ArrayOfConnectionContract(struct soap*, const char*, ns3__ArrayOfConnectionContract *, const char*);

#ifndef soap_write_ns3__ArrayOfConnectionContract
#define soap_write_ns3__ArrayOfConnectionContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:ArrayOfConnectionContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ArrayOfConnectionContract * SOAP_FMAC4 soap_get_ns3__ArrayOfConnectionContract(struct soap*, ns3__ArrayOfConnectionContract *, const char*, const char*);

#ifndef soap_read_ns3__ArrayOfConnectionContract
#define soap_read_ns3__ArrayOfConnectionContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__ArrayOfConnectionContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__ArrayOfConnectionContract * SOAP_FMAC2 soap_instantiate_ns3__ArrayOfConnectionContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__ArrayOfConnectionContract * soap_new_ns3__ArrayOfConnectionContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__ArrayOfConnectionContract(soap, n, NULL, NULL, NULL); }

inline ns3__ArrayOfConnectionContract * soap_new_req_ns3__ArrayOfConnectionContract(struct soap *soap) { ns3__ArrayOfConnectionContract *_p = soap_instantiate_ns3__ArrayOfConnectionContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__ArrayOfConnectionContract * soap_new_set_ns3__ArrayOfConnectionContract(struct soap *soap, std::vector<ns3__ConnectionContract * >& ConnectionContract) { ns3__ArrayOfConnectionContract *_p = soap_instantiate_ns3__ArrayOfConnectionContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__ArrayOfConnectionContract::ConnectionContract = ConnectionContract; } return _p; }

inline void soap_delete_ns3__ArrayOfConnectionContract(struct soap *soap, ns3__ArrayOfConnectionContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__ArrayOfConnectionContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns3__UserContract
#define SOAP_TYPE_ns3__UserContract (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns3__UserContract(struct soap*, const char*, int, const ns3__UserContract *, const char*);
SOAP_FMAC3 ns3__UserContract * SOAP_FMAC4 soap_in_ns3__UserContract(struct soap*, const char*, ns3__UserContract *, const char*);

#ifndef soap_write_ns3__UserContract
#define soap_write_ns3__UserContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns3:UserContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__UserContract * SOAP_FMAC4 soap_get_ns3__UserContract(struct soap*, ns3__UserContract *, const char*, const char*);

#ifndef soap_read_ns3__UserContract
#define soap_read_ns3__UserContract(soap, data) ( soap_begin_recv(soap) || !soap_get_ns3__UserContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 ns3__UserContract * SOAP_FMAC2 soap_instantiate_ns3__UserContract(struct soap*, int, const char*, const char*, size_t*);

inline ns3__UserContract * soap_new_ns3__UserContract(struct soap *soap, int n = -1) { return soap_instantiate_ns3__UserContract(soap, n, NULL, NULL, NULL); }

inline ns3__UserContract * soap_new_req_ns3__UserContract(struct soap *soap) { ns3__UserContract *_p = soap_instantiate_ns3__UserContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline ns3__UserContract * soap_new_set_ns3__UserContract(struct soap *soap, ns3__ArrayOfConnectionContract *Connections, std::string *Email, ns3__HumorContract *Humor, ns3__ArrayOfUserTagContract *UserTags) { ns3__UserContract *_p = soap_instantiate_ns3__UserContract(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->ns3__UserContract::Connections = Connections; _p->ns3__UserContract::Email = Email; _p->ns3__UserContract::Humor = Humor; _p->ns3__UserContract::UserTags = UserTags; } return _p; }

inline void soap_delete_ns3__UserContract(struct soap *soap, ns3__UserContract *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns3__UserContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__LogoutResponse
#define SOAP_TYPE__ns1__LogoutResponse (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__LogoutResponse(struct soap*, const char*, int, const _ns1__LogoutResponse *, const char*);
SOAP_FMAC3 _ns1__LogoutResponse * SOAP_FMAC4 soap_in__ns1__LogoutResponse(struct soap*, const char*, _ns1__LogoutResponse *, const char*);

#ifndef soap_write__ns1__LogoutResponse
#define soap_write__ns1__LogoutResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:LogoutResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LogoutResponse * SOAP_FMAC4 soap_get__ns1__LogoutResponse(struct soap*, _ns1__LogoutResponse *, const char*, const char*);

#ifndef soap_read__ns1__LogoutResponse
#define soap_read__ns1__LogoutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__LogoutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__LogoutResponse * SOAP_FMAC2 soap_instantiate__ns1__LogoutResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__LogoutResponse * soap_new__ns1__LogoutResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__LogoutResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__LogoutResponse * soap_new_req__ns1__LogoutResponse(struct soap *soap) { _ns1__LogoutResponse *_p = soap_instantiate__ns1__LogoutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__LogoutResponse * soap_new_set__ns1__LogoutResponse(struct soap *soap) { _ns1__LogoutResponse *_p = soap_instantiate__ns1__LogoutResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline void soap_delete__ns1__LogoutResponse(struct soap *soap, _ns1__LogoutResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__LogoutResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Logout
#define SOAP_TYPE__ns1__Logout (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Logout(struct soap*, const char*, int, const _ns1__Logout *, const char*);
SOAP_FMAC3 _ns1__Logout * SOAP_FMAC4 soap_in__ns1__Logout(struct soap*, const char*, _ns1__Logout *, const char*);

#ifndef soap_write__ns1__Logout
#define soap_write__ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Logout * SOAP_FMAC4 soap_get__ns1__Logout(struct soap*, _ns1__Logout *, const char*, const char*);

#ifndef soap_read__ns1__Logout
#define soap_read__ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__Logout * SOAP_FMAC2 soap_instantiate__ns1__Logout(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__Logout * soap_new__ns1__Logout(struct soap *soap, int n = -1) { return soap_instantiate__ns1__Logout(soap, n, NULL, NULL, NULL); }

inline _ns1__Logout * soap_new_req__ns1__Logout(struct soap *soap) { _ns1__Logout *_p = soap_instantiate__ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__Logout * soap_new_set__ns1__Logout(struct soap *soap, std::string *Token) { _ns1__Logout *_p = soap_instantiate__ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Logout::Token = Token; } return _p; }

inline void soap_delete__ns1__Logout(struct soap *soap, _ns1__Logout *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Logout(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetGraphResponse
#define SOAP_TYPE__ns1__GetGraphResponse (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetGraphResponse(struct soap*, const char*, int, const _ns1__GetGraphResponse *, const char*);
SOAP_FMAC3 _ns1__GetGraphResponse * SOAP_FMAC4 soap_in__ns1__GetGraphResponse(struct soap*, const char*, _ns1__GetGraphResponse *, const char*);

#ifndef soap_write__ns1__GetGraphResponse
#define soap_write__ns1__GetGraphResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetGraphResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetGraphResponse * SOAP_FMAC4 soap_get__ns1__GetGraphResponse(struct soap*, _ns1__GetGraphResponse *, const char*, const char*);

#ifndef soap_read__ns1__GetGraphResponse
#define soap_read__ns1__GetGraphResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetGraphResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetGraphResponse * SOAP_FMAC2 soap_instantiate__ns1__GetGraphResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetGraphResponse * soap_new__ns1__GetGraphResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetGraphResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__GetGraphResponse * soap_new_req__ns1__GetGraphResponse(struct soap *soap) { _ns1__GetGraphResponse *_p = soap_instantiate__ns1__GetGraphResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetGraphResponse * soap_new_set__ns1__GetGraphResponse(struct soap *soap, ns3__UserContract *GetGraphResult) { _ns1__GetGraphResponse *_p = soap_instantiate__ns1__GetGraphResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetGraphResponse::GetGraphResult = GetGraphResult; } return _p; }

inline void soap_delete__ns1__GetGraphResponse(struct soap *soap, _ns1__GetGraphResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetGraphResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__GetGraph
#define SOAP_TYPE__ns1__GetGraph (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__GetGraph(struct soap*, const char*, int, const _ns1__GetGraph *, const char*);
SOAP_FMAC3 _ns1__GetGraph * SOAP_FMAC4 soap_in__ns1__GetGraph(struct soap*, const char*, _ns1__GetGraph *, const char*);

#ifndef soap_write__ns1__GetGraph
#define soap_write__ns1__GetGraph(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:GetGraph", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetGraph * SOAP_FMAC4 soap_get__ns1__GetGraph(struct soap*, _ns1__GetGraph *, const char*, const char*);

#ifndef soap_read__ns1__GetGraph
#define soap_read__ns1__GetGraph(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__GetGraph(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__GetGraph * SOAP_FMAC2 soap_instantiate__ns1__GetGraph(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__GetGraph * soap_new__ns1__GetGraph(struct soap *soap, int n = -1) { return soap_instantiate__ns1__GetGraph(soap, n, NULL, NULL, NULL); }

inline _ns1__GetGraph * soap_new_req__ns1__GetGraph(struct soap *soap) { _ns1__GetGraph *_p = soap_instantiate__ns1__GetGraph(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__GetGraph * soap_new_set__ns1__GetGraph(struct soap *soap, std::string *Token, std::string *Email, int *graphDepth) { _ns1__GetGraph *_p = soap_instantiate__ns1__GetGraph(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__GetGraph::Token = Token; _p->_ns1__GetGraph::Email = Email; _p->_ns1__GetGraph::graphDepth = graphDepth; } return _p; }

inline void soap_delete__ns1__GetGraph(struct soap *soap, _ns1__GetGraph *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__GetGraph(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__LoginResponse
#define SOAP_TYPE__ns1__LoginResponse (9)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__LoginResponse(struct soap*, const char*, int, const _ns1__LoginResponse *, const char*);
SOAP_FMAC3 _ns1__LoginResponse * SOAP_FMAC4 soap_in__ns1__LoginResponse(struct soap*, const char*, _ns1__LoginResponse *, const char*);

#ifndef soap_write__ns1__LoginResponse
#define soap_write__ns1__LoginResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:LoginResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LoginResponse * SOAP_FMAC4 soap_get__ns1__LoginResponse(struct soap*, _ns1__LoginResponse *, const char*, const char*);

#ifndef soap_read__ns1__LoginResponse
#define soap_read__ns1__LoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__LoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__LoginResponse * SOAP_FMAC2 soap_instantiate__ns1__LoginResponse(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__LoginResponse * soap_new__ns1__LoginResponse(struct soap *soap, int n = -1) { return soap_instantiate__ns1__LoginResponse(soap, n, NULL, NULL, NULL); }

inline _ns1__LoginResponse * soap_new_req__ns1__LoginResponse(struct soap *soap) { _ns1__LoginResponse *_p = soap_instantiate__ns1__LoginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__LoginResponse * soap_new_set__ns1__LoginResponse(struct soap *soap, std::string *LoginResult) { _ns1__LoginResponse *_p = soap_instantiate__ns1__LoginResponse(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__LoginResponse::LoginResult = LoginResult; } return _p; }

inline void soap_delete__ns1__LoginResponse(struct soap *soap, _ns1__LoginResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__LoginResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__ns1__Login
#define SOAP_TYPE__ns1__Login (8)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__ns1__Login(struct soap*, const char*, int, const _ns1__Login *, const char*);
SOAP_FMAC3 _ns1__Login * SOAP_FMAC4 soap_in__ns1__Login(struct soap*, const char*, _ns1__Login *, const char*);

#ifndef soap_write__ns1__Login
#define soap_write__ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || ((data)->soap_serialize(soap),0) || (data)->soap_put(soap, "ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Login * SOAP_FMAC4 soap_get__ns1__Login(struct soap*, _ns1__Login *, const char*, const char*);

#ifndef soap_read__ns1__Login
#define soap_read__ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get__ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 _ns1__Login * SOAP_FMAC2 soap_instantiate__ns1__Login(struct soap*, int, const char*, const char*, size_t*);

inline _ns1__Login * soap_new__ns1__Login(struct soap *soap, int n = -1) { return soap_instantiate__ns1__Login(soap, n, NULL, NULL, NULL); }

inline _ns1__Login * soap_new_req__ns1__Login(struct soap *soap) { _ns1__Login *_p = soap_instantiate__ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); } return _p; }

inline _ns1__Login * soap_new_set__ns1__Login(struct soap *soap, std::string *Email, std::string *Password) { _ns1__Login *_p = soap_instantiate__ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { _p->soap_default(soap); _p->_ns1__Login::Email = Email; _p->_ns1__Login::Password = Password; } return _p; }

inline void soap_delete__ns1__Login(struct soap *soap, _ns1__Login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy__ns1__Login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data),0) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data),0) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data),0) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data),0) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data),0) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns1__Logout
#define SOAP_TYPE___ns1__Logout (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Logout(struct soap*, struct __ns1__Logout *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Logout(struct soap*, const struct __ns1__Logout *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Logout(struct soap*, const char*, int, const struct __ns1__Logout *, const char*);
SOAP_FMAC3 struct __ns1__Logout * SOAP_FMAC4 soap_in___ns1__Logout(struct soap*, const char*, struct __ns1__Logout *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Logout(struct soap*, const struct __ns1__Logout *, const char*, const char*);

#ifndef soap_write___ns1__Logout
#define soap_write___ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Logout(soap, data),0) || soap_put___ns1__Logout(soap, data, "-ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Logout * SOAP_FMAC4 soap_get___ns1__Logout(struct soap*, struct __ns1__Logout *, const char*, const char*);

#ifndef soap_read___ns1__Logout
#define soap_read___ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Logout * SOAP_FMAC2 soap_instantiate___ns1__Logout(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Logout * soap_new___ns1__Logout(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Logout(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Logout * soap_new_req___ns1__Logout(struct soap *soap) { struct __ns1__Logout *_p = soap_instantiate___ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout(soap, _p); } return _p; }

inline struct __ns1__Logout * soap_new_set___ns1__Logout(struct soap *soap, _ns1__Logout *ns1__Logout) { struct __ns1__Logout *_p = soap_instantiate___ns1__Logout(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Logout(soap, _p); _p->ns1__Logout = ns1__Logout; } return _p; }

inline void soap_delete___ns1__Logout(struct soap *soap, struct __ns1__Logout *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Logout(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__GetGraph
#define SOAP_TYPE___ns1__GetGraph (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__GetGraph(struct soap*, struct __ns1__GetGraph *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__GetGraph(struct soap*, const struct __ns1__GetGraph *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__GetGraph(struct soap*, const char*, int, const struct __ns1__GetGraph *, const char*);
SOAP_FMAC3 struct __ns1__GetGraph * SOAP_FMAC4 soap_in___ns1__GetGraph(struct soap*, const char*, struct __ns1__GetGraph *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__GetGraph(struct soap*, const struct __ns1__GetGraph *, const char*, const char*);

#ifndef soap_write___ns1__GetGraph
#define soap_write___ns1__GetGraph(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__GetGraph(soap, data),0) || soap_put___ns1__GetGraph(soap, data, "-ns1:GetGraph", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__GetGraph * SOAP_FMAC4 soap_get___ns1__GetGraph(struct soap*, struct __ns1__GetGraph *, const char*, const char*);

#ifndef soap_read___ns1__GetGraph
#define soap_read___ns1__GetGraph(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__GetGraph(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__GetGraph * SOAP_FMAC2 soap_instantiate___ns1__GetGraph(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__GetGraph * soap_new___ns1__GetGraph(struct soap *soap, int n = -1) { return soap_instantiate___ns1__GetGraph(soap, n, NULL, NULL, NULL); }

inline struct __ns1__GetGraph * soap_new_req___ns1__GetGraph(struct soap *soap) { struct __ns1__GetGraph *_p = soap_instantiate___ns1__GetGraph(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetGraph(soap, _p); } return _p; }

inline struct __ns1__GetGraph * soap_new_set___ns1__GetGraph(struct soap *soap, _ns1__GetGraph *ns1__GetGraph) { struct __ns1__GetGraph *_p = soap_instantiate___ns1__GetGraph(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__GetGraph(soap, _p); _p->ns1__GetGraph = ns1__GetGraph; } return _p; }

inline void soap_delete___ns1__GetGraph(struct soap *soap, struct __ns1__GetGraph *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__GetGraph(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns1__Login
#define SOAP_TYPE___ns1__Login (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns1__Login(struct soap*, struct __ns1__Login *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns1__Login(struct soap*, const struct __ns1__Login *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns1__Login(struct soap*, const char*, int, const struct __ns1__Login *, const char*);
SOAP_FMAC3 struct __ns1__Login * SOAP_FMAC4 soap_in___ns1__Login(struct soap*, const char*, struct __ns1__Login *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns1__Login(struct soap*, const struct __ns1__Login *, const char*, const char*);

#ifndef soap_write___ns1__Login
#define soap_write___ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize___ns1__Login(soap, data),0) || soap_put___ns1__Login(soap, data, "-ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct __ns1__Login * SOAP_FMAC4 soap_get___ns1__Login(struct soap*, struct __ns1__Login *, const char*, const char*);

#ifndef soap_read___ns1__Login
#define soap_read___ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get___ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif

SOAP_FMAC1 struct __ns1__Login * SOAP_FMAC2 soap_instantiate___ns1__Login(struct soap*, int, const char*, const char*, size_t*);

inline struct __ns1__Login * soap_new___ns1__Login(struct soap *soap, int n = -1) { return soap_instantiate___ns1__Login(soap, n, NULL, NULL, NULL); }

inline struct __ns1__Login * soap_new_req___ns1__Login(struct soap *soap) { struct __ns1__Login *_p = soap_instantiate___ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login(soap, _p); } return _p; }

inline struct __ns1__Login * soap_new_set___ns1__Login(struct soap *soap, _ns1__Login *ns1__Login) { struct __ns1__Login *_p = soap_instantiate___ns1__Login(soap, -1, NULL, NULL, NULL); if (_p) { soap_default___ns1__Login(soap, _p); _p->ns1__Login = ns1__Login; } return _p; }

inline void soap_delete___ns1__Login(struct soap *soap, struct __ns1__Login *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns1__Login(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data),0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data),0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data),0) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#endif

#ifndef SOAP_TYPE_PointerTo_ns1__LogoutResponse
#define SOAP_TYPE_PointerTo_ns1__LogoutResponse (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__LogoutResponse(struct soap*, _ns1__LogoutResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__LogoutResponse(struct soap*, const char *, int, _ns1__LogoutResponse *const*, const char *);
SOAP_FMAC3 _ns1__LogoutResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__LogoutResponse(struct soap*, const char*, _ns1__LogoutResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__LogoutResponse(struct soap*, _ns1__LogoutResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__LogoutResponse
#define soap_write_PointerTo_ns1__LogoutResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__LogoutResponse(soap, data),0) || soap_put_PointerTo_ns1__LogoutResponse(soap, data, "ns1:LogoutResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LogoutResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__LogoutResponse(struct soap*, _ns1__LogoutResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__LogoutResponse
#define soap_read_PointerTo_ns1__LogoutResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__LogoutResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__Logout
#define SOAP_TYPE_PointerTo_ns1__Logout (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Logout(struct soap*, _ns1__Logout *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Logout(struct soap*, const char *, int, _ns1__Logout *const*, const char *);
SOAP_FMAC3 _ns1__Logout ** SOAP_FMAC4 soap_in_PointerTo_ns1__Logout(struct soap*, const char*, _ns1__Logout **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Logout(struct soap*, _ns1__Logout *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__Logout
#define soap_write_PointerTo_ns1__Logout(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Logout(soap, data),0) || soap_put_PointerTo_ns1__Logout(soap, data, "ns1:Logout", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Logout ** SOAP_FMAC4 soap_get_PointerTo_ns1__Logout(struct soap*, _ns1__Logout **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Logout
#define soap_read_PointerTo_ns1__Logout(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Logout(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__GetGraphResponse
#define SOAP_TYPE_PointerTo_ns1__GetGraphResponse (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetGraphResponse(struct soap*, _ns1__GetGraphResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetGraphResponse(struct soap*, const char *, int, _ns1__GetGraphResponse *const*, const char *);
SOAP_FMAC3 _ns1__GetGraphResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetGraphResponse(struct soap*, const char*, _ns1__GetGraphResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetGraphResponse(struct soap*, _ns1__GetGraphResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__GetGraphResponse
#define soap_write_PointerTo_ns1__GetGraphResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetGraphResponse(soap, data),0) || soap_put_PointerTo_ns1__GetGraphResponse(soap, data, "ns1:GetGraphResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetGraphResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetGraphResponse(struct soap*, _ns1__GetGraphResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetGraphResponse
#define soap_read_PointerTo_ns1__GetGraphResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetGraphResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__GetGraph
#define SOAP_TYPE_PointerTo_ns1__GetGraph (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__GetGraph(struct soap*, _ns1__GetGraph *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__GetGraph(struct soap*, const char *, int, _ns1__GetGraph *const*, const char *);
SOAP_FMAC3 _ns1__GetGraph ** SOAP_FMAC4 soap_in_PointerTo_ns1__GetGraph(struct soap*, const char*, _ns1__GetGraph **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__GetGraph(struct soap*, _ns1__GetGraph *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__GetGraph
#define soap_write_PointerTo_ns1__GetGraph(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__GetGraph(soap, data),0) || soap_put_PointerTo_ns1__GetGraph(soap, data, "ns1:GetGraph", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__GetGraph ** SOAP_FMAC4 soap_get_PointerTo_ns1__GetGraph(struct soap*, _ns1__GetGraph **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__GetGraph
#define soap_read_PointerTo_ns1__GetGraph(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__GetGraph(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__LoginResponse
#define SOAP_TYPE_PointerTo_ns1__LoginResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__LoginResponse(struct soap*, _ns1__LoginResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__LoginResponse(struct soap*, const char *, int, _ns1__LoginResponse *const*, const char *);
SOAP_FMAC3 _ns1__LoginResponse ** SOAP_FMAC4 soap_in_PointerTo_ns1__LoginResponse(struct soap*, const char*, _ns1__LoginResponse **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__LoginResponse(struct soap*, _ns1__LoginResponse *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__LoginResponse
#define soap_write_PointerTo_ns1__LoginResponse(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__LoginResponse(soap, data),0) || soap_put_PointerTo_ns1__LoginResponse(soap, data, "ns1:LoginResponse", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__LoginResponse ** SOAP_FMAC4 soap_get_PointerTo_ns1__LoginResponse(struct soap*, _ns1__LoginResponse **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__LoginResponse
#define soap_read_PointerTo_ns1__LoginResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__LoginResponse(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTo_ns1__Login
#define SOAP_TYPE_PointerTo_ns1__Login (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_ns1__Login(struct soap*, _ns1__Login *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_ns1__Login(struct soap*, const char *, int, _ns1__Login *const*, const char *);
SOAP_FMAC3 _ns1__Login ** SOAP_FMAC4 soap_in_PointerTo_ns1__Login(struct soap*, const char*, _ns1__Login **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_ns1__Login(struct soap*, _ns1__Login *const*, const char*, const char*);

#ifndef soap_write_PointerTo_ns1__Login
#define soap_write_PointerTo_ns1__Login(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTo_ns1__Login(soap, data),0) || soap_put_PointerTo_ns1__Login(soap, data, "ns1:Login", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 _ns1__Login ** SOAP_FMAC4 soap_get_PointerTo_ns1__Login(struct soap*, _ns1__Login **, const char*, const char*);

#ifndef soap_read_PointerTo_ns1__Login
#define soap_read_PointerTo_ns1__Login(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTo_ns1__Login(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__UserTagContract
#define SOAP_TYPE_PointerTons3__UserTagContract (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__UserTagContract(struct soap*, ns3__UserTagContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__UserTagContract(struct soap*, const char *, int, ns3__UserTagContract *const*, const char *);
SOAP_FMAC3 ns3__UserTagContract ** SOAP_FMAC4 soap_in_PointerTons3__UserTagContract(struct soap*, const char*, ns3__UserTagContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__UserTagContract(struct soap*, ns3__UserTagContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__UserTagContract
#define soap_write_PointerTons3__UserTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__UserTagContract(soap, data),0) || soap_put_PointerTons3__UserTagContract(soap, data, "ns3:UserTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__UserTagContract ** SOAP_FMAC4 soap_get_PointerTons3__UserTagContract(struct soap*, ns3__UserTagContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__UserTagContract
#define soap_read_PointerTons3__UserTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__UserTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__ConnectionTagContract
#define SOAP_TYPE_PointerTons3__ConnectionTagContract (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ConnectionTagContract(struct soap*, ns3__ConnectionTagContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ConnectionTagContract(struct soap*, const char *, int, ns3__ConnectionTagContract *const*, const char *);
SOAP_FMAC3 ns3__ConnectionTagContract ** SOAP_FMAC4 soap_in_PointerTons3__ConnectionTagContract(struct soap*, const char*, ns3__ConnectionTagContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ConnectionTagContract(struct soap*, ns3__ConnectionTagContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__ConnectionTagContract
#define soap_write_PointerTons3__ConnectionTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__ConnectionTagContract(soap, data),0) || soap_put_PointerTons3__ConnectionTagContract(soap, data, "ns3:ConnectionTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ConnectionTagContract ** SOAP_FMAC4 soap_get_PointerTons3__ConnectionTagContract(struct soap*, ns3__ConnectionTagContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__ConnectionTagContract
#define soap_read_PointerTons3__ConnectionTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__ConnectionTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__ConnectionContract
#define SOAP_TYPE_PointerTons3__ConnectionContract (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ConnectionContract(struct soap*, ns3__ConnectionContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ConnectionContract(struct soap*, const char *, int, ns3__ConnectionContract *const*, const char *);
SOAP_FMAC3 ns3__ConnectionContract ** SOAP_FMAC4 soap_in_PointerTons3__ConnectionContract(struct soap*, const char*, ns3__ConnectionContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ConnectionContract(struct soap*, ns3__ConnectionContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__ConnectionContract
#define soap_write_PointerTons3__ConnectionContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__ConnectionContract(soap, data),0) || soap_put_PointerTons3__ConnectionContract(soap, data, "ns3:ConnectionContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ConnectionContract ** SOAP_FMAC4 soap_get_PointerTons3__ConnectionContract(struct soap*, ns3__ConnectionContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__ConnectionContract
#define soap_read_PointerTons3__ConnectionContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__ConnectionContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__ArrayOfUserTagContract
#define SOAP_TYPE_PointerTons3__ArrayOfUserTagContract (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ArrayOfUserTagContract(struct soap*, ns3__ArrayOfUserTagContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ArrayOfUserTagContract(struct soap*, const char *, int, ns3__ArrayOfUserTagContract *const*, const char *);
SOAP_FMAC3 ns3__ArrayOfUserTagContract ** SOAP_FMAC4 soap_in_PointerTons3__ArrayOfUserTagContract(struct soap*, const char*, ns3__ArrayOfUserTagContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ArrayOfUserTagContract(struct soap*, ns3__ArrayOfUserTagContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__ArrayOfUserTagContract
#define soap_write_PointerTons3__ArrayOfUserTagContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__ArrayOfUserTagContract(soap, data),0) || soap_put_PointerTons3__ArrayOfUserTagContract(soap, data, "ns3:ArrayOfUserTagContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ArrayOfUserTagContract ** SOAP_FMAC4 soap_get_PointerTons3__ArrayOfUserTagContract(struct soap*, ns3__ArrayOfUserTagContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__ArrayOfUserTagContract
#define soap_read_PointerTons3__ArrayOfUserTagContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__ArrayOfUserTagContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__HumorContract
#define SOAP_TYPE_PointerTons3__HumorContract (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__HumorContract(struct soap*, ns3__HumorContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__HumorContract(struct soap*, const char *, int, ns3__HumorContract *const*, const char *);
SOAP_FMAC3 ns3__HumorContract ** SOAP_FMAC4 soap_in_PointerTons3__HumorContract(struct soap*, const char*, ns3__HumorContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__HumorContract(struct soap*, ns3__HumorContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__HumorContract
#define soap_write_PointerTons3__HumorContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__HumorContract(soap, data),0) || soap_put_PointerTons3__HumorContract(soap, data, "ns3:HumorContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__HumorContract ** SOAP_FMAC4 soap_get_PointerTons3__HumorContract(struct soap*, ns3__HumorContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__HumorContract
#define soap_read_PointerTons3__HumorContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__HumorContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__ArrayOfConnectionContract
#define SOAP_TYPE_PointerTons3__ArrayOfConnectionContract (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__ArrayOfConnectionContract(struct soap*, ns3__ArrayOfConnectionContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__ArrayOfConnectionContract(struct soap*, const char *, int, ns3__ArrayOfConnectionContract *const*, const char *);
SOAP_FMAC3 ns3__ArrayOfConnectionContract ** SOAP_FMAC4 soap_in_PointerTons3__ArrayOfConnectionContract(struct soap*, const char*, ns3__ArrayOfConnectionContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__ArrayOfConnectionContract(struct soap*, ns3__ArrayOfConnectionContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__ArrayOfConnectionContract
#define soap_write_PointerTons3__ArrayOfConnectionContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__ArrayOfConnectionContract(soap, data),0) || soap_put_PointerTons3__ArrayOfConnectionContract(soap, data, "ns3:ArrayOfConnectionContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__ArrayOfConnectionContract ** SOAP_FMAC4 soap_get_PointerTons3__ArrayOfConnectionContract(struct soap*, ns3__ArrayOfConnectionContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__ArrayOfConnectionContract
#define soap_read_PointerTons3__ArrayOfConnectionContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__ArrayOfConnectionContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTons3__UserContract
#define SOAP_TYPE_PointerTons3__UserContract (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons3__UserContract(struct soap*, ns3__UserContract *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons3__UserContract(struct soap*, const char *, int, ns3__UserContract *const*, const char *);
SOAP_FMAC3 ns3__UserContract ** SOAP_FMAC4 soap_in_PointerTons3__UserContract(struct soap*, const char*, ns3__UserContract **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons3__UserContract(struct soap*, ns3__UserContract *const*, const char*, const char*);

#ifndef soap_write_PointerTons3__UserContract
#define soap_write_PointerTons3__UserContract(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTons3__UserContract(soap, data),0) || soap_put_PointerTons3__UserContract(soap, data, "ns3:UserContract", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 ns3__UserContract ** SOAP_FMAC4 soap_get_PointerTons3__UserContract(struct soap*, ns3__UserContract **, const char*, const char*);

#ifndef soap_read_PointerTons3__UserContract
#define soap_read_PointerTons3__UserContract(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons3__UserContract(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);

#ifndef soap_write_PointerToint
#define soap_write_PointerToint(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerToint(soap, data),0) || soap_put_PointerToint(soap, data, "int", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);

#ifndef soap_read_PointerToint
#define soap_read_PointerToint(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToint(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_PointerTostd__string
#define SOAP_TYPE_PointerTostd__string (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostd__string(struct soap*, std::string *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostd__string(struct soap*, const char *, int, std::string *const*, const char *);
SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_in_PointerTostd__string(struct soap*, const char*, std::string **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostd__string(struct soap*, std::string *const*, const char*, const char*);

#ifndef soap_write_PointerTostd__string
#define soap_write_PointerTostd__string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_PointerTostd__string(soap, data),0) || soap_put_PointerTostd__string(soap, data, "string", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 std::string ** SOAP_FMAC4 soap_get_PointerTostd__string(struct soap*, std::string **, const char*, const char*);

#ifndef soap_read_PointerTostd__string
#define soap_read_PointerTostd__string(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTostd__string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize__QName(soap, data),0) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_free_temp(soap), soap_begin_send(soap) || (soap_serialize_string(soap, data),0) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), (soap)->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), (soap)->error )
#endif


#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons3__UserTagContract
#define SOAP_TYPE_std__vectorTemplateOfPointerTons3__UserTagContract (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, std::vector<ns3__UserTagContract * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, const std::vector<ns3__UserTagContract * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, const char*, int, const std::vector<ns3__UserTagContract * >*, const char*);
SOAP_FMAC3 std::vector<ns3__UserTagContract * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, const char*, std::vector<ns3__UserTagContract * >*, const char*);
SOAP_FMAC1 std::vector<ns3__UserTagContract * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, int, const char*, const char*, size_t*);

inline std::vector<ns3__UserTagContract * > * soap_new_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap *soap, int n = -1) { return soap_instantiate_std__vectorTemplateOfPointerTons3__UserTagContract(soap, n, NULL, NULL, NULL); }

inline void soap_delete_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap *soap, std::vector<ns3__UserTagContract * >*p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons3__UserTagContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons3__ConnectionContract
#define SOAP_TYPE_std__vectorTemplateOfPointerTons3__ConnectionContract (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, std::vector<ns3__ConnectionContract * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, const std::vector<ns3__ConnectionContract * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, const char*, int, const std::vector<ns3__ConnectionContract * >*, const char*);
SOAP_FMAC3 std::vector<ns3__ConnectionContract * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, const char*, std::vector<ns3__ConnectionContract * >*, const char*);
SOAP_FMAC1 std::vector<ns3__ConnectionContract * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, int, const char*, const char*, size_t*);

inline std::vector<ns3__ConnectionContract * > * soap_new_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap *soap, int n = -1) { return soap_instantiate_std__vectorTemplateOfPointerTons3__ConnectionContract(soap, n, NULL, NULL, NULL); }

inline void soap_delete_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap *soap, std::vector<ns3__ConnectionContract * >*p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons3__ConnectionContract(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
