//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialGameWebsite.SocialGameBLLService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL")]
    [System.SerializableAttribute()]
    internal partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime BirthdateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FacebookProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HumourStatusIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] InterestsIDsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LinkedInProfileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal System.DateTime Birthdate {
            get {
                return this.BirthdateField;
            }
            set {
                if ((this.BirthdateField.Equals(value) != true)) {
                    this.BirthdateField = value;
                    this.RaisePropertyChanged("Birthdate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string FacebookProfile {
            get {
                return this.FacebookProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.FacebookProfileField, value) != true)) {
                    this.FacebookProfileField = value;
                    this.RaisePropertyChanged("FacebookProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int HumourStatusId {
            get {
                return this.HumourStatusIdField;
            }
            set {
                if ((this.HumourStatusIdField.Equals(value) != true)) {
                    this.HumourStatusIdField = value;
                    this.RaisePropertyChanged("HumourStatusId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int[] InterestsIDs {
            get {
                return this.InterestsIDsField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestsIDsField, value) != true)) {
                    this.InterestsIDsField = value;
                    this.RaisePropertyChanged("InterestsIDs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string LinkedInProfile {
            get {
                return this.LinkedInProfileField;
            }
            set {
                if ((object.ReferenceEquals(this.LinkedInProfileField, value) != true)) {
                    this.LinkedInProfileField = value;
                    this.RaisePropertyChanged("LinkedInProfile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HumourStatus", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class HumourStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationshipTag", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class RelationshipTag : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Relationship", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class Relationship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelationshipTagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrengthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserAEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserBEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int RelationshipTagId {
            get {
                return this.RelationshipTagIdField;
            }
            set {
                if ((this.RelationshipTagIdField.Equals(value) != true)) {
                    this.RelationshipTagIdField = value;
                    this.RaisePropertyChanged("RelationshipTagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((this.StrengthField.Equals(value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserAEmail {
            get {
                return this.UserAEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAEmailField, value) != true)) {
                    this.UserAEmailField = value;
                    this.RaisePropertyChanged("UserAEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserBEmail {
            get {
                return this.UserBEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserBEmailField, value) != true)) {
                    this.UserBEmailField = value;
                    this.RaisePropertyChanged("UserBEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Graph", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class Graph : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGameWebsite.SocialGameBLLService.HumourStatus[] HumourStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGameWebsite.SocialGameBLLService.Interest[] InterestsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGameWebsite.SocialGameBLLService.RelationshipTag[] RelationshipTagsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGameWebsite.SocialGameBLLService.Relationship[] RelationshipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private SocialGameWebsite.SocialGameBLLService.User[] UsersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SocialGameWebsite.SocialGameBLLService.HumourStatus[] HumourStatus {
            get {
                return this.HumourStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.HumourStatusField, value) != true)) {
                    this.HumourStatusField = value;
                    this.RaisePropertyChanged("HumourStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SocialGameWebsite.SocialGameBLLService.Interest[] Interests {
            get {
                return this.InterestsField;
            }
            set {
                if ((object.ReferenceEquals(this.InterestsField, value) != true)) {
                    this.InterestsField = value;
                    this.RaisePropertyChanged("Interests");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SocialGameWebsite.SocialGameBLLService.RelationshipTag[] RelationshipTags {
            get {
                return this.RelationshipTagsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipTagsField, value) != true)) {
                    this.RelationshipTagsField = value;
                    this.RaisePropertyChanged("RelationshipTags");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SocialGameWebsite.SocialGameBLLService.Relationship[] Relationships {
            get {
                return this.RelationshipsField;
            }
            set {
                if ((object.ReferenceEquals(this.RelationshipsField, value) != true)) {
                    this.RelationshipsField = value;
                    this.RaisePropertyChanged("Relationships");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal SocialGameWebsite.SocialGameBLLService.User[] Users {
            get {
                return this.UsersField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersField, value) != true)) {
                    this.UsersField = value;
                    this.RaisePropertyChanged("Users");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Interest", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class Interest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelationshipRequest", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class RelationshipRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RelationshipTagIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestedEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequesterEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StrengthField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int RelationshipTagId {
            get {
                return this.RelationshipTagIdField;
            }
            set {
                if ((this.RelationshipTagIdField.Equals(value) != true)) {
                    this.RelationshipTagIdField = value;
                    this.RaisePropertyChanged("RelationshipTagId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RequestedEmail {
            get {
                return this.RequestedEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestedEmailField, value) != true)) {
                    this.RequestedEmailField = value;
                    this.RaisePropertyChanged("RequestedEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string RequesterEmail {
            get {
                return this.RequesterEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.RequesterEmailField, value) != true)) {
                    this.RequesterEmailField = value;
                    this.RaisePropertyChanged("RequesterEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int Strength {
            get {
                return this.StrengthField;
            }
            set {
                if ((this.StrengthField.Equals(value) != true)) {
                    this.StrengthField = value;
                    this.RaisePropertyChanged("Strength");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NetworkStatistics", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class NetworkStatistics : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RelationshipStrenghtAverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal double RelationshipStrenghtAverage {
            get {
                return this.RelationshipStrenghtAverageField;
            }
            set {
                if ((this.RelationshipStrenghtAverageField.Equals(value) != true)) {
                    this.RelationshipStrenghtAverageField = value;
                    this.RaisePropertyChanged("RelationshipStrenghtAverage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int UserCount {
            get {
                return this.UserCountField;
            }
            set {
                if ((this.UserCountField.Equals(value) != true)) {
                    this.UserCountField = value;
                    this.RaisePropertyChanged("UserCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserScore", Namespace="http://schemas.datacontract.org/2004/07/SocialGameBLL.Service")]
    [System.SerializableAttribute()]
    internal partial class UserScore : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float UserPointsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserSurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal int UserLevel {
            get {
                return this.UserLevelField;
            }
            set {
                if ((this.UserLevelField.Equals(value) != true)) {
                    this.UserLevelField = value;
                    this.RaisePropertyChanged("UserLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal float UserPoints {
            get {
                return this.UserPointsField;
            }
            set {
                if ((this.UserPointsField.Equals(value) != true)) {
                    this.UserPointsField = value;
                    this.RaisePropertyChanged("UserPoints");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        internal string UserSurname {
            get {
                return this.UserSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserSurnameField, value) != true)) {
                    this.UserSurnameField = value;
                    this.RaisePropertyChanged("UserSurname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SocialGameBLLService.ISocialGameBLLService")]
    internal interface ISocialGameBLLService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetData", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetData", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContractResponse")]
        SocialGameWebsite.SocialGameBLLService.CompositeType GetDataUsingDataContract(SocialGameWebsite.SocialGameBLLService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.CompositeType> GetDataUsingDataContractAsync(SocialGameWebsite.SocialGameBLLService.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RegisterUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RegisterUserResponse")]
        SocialGameWebsite.SocialGameBLLService.User RegisterUser(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RegisterUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RegisterUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> RegisterUserAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/LoginUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/LoginUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/ISocialGameBLLService/LoginUserFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        SocialGameWebsite.SocialGameBLLService.User LoginUser(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/LoginUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/LoginUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> LoginUserAsync(string Email, string Password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserResponse")]
        SocialGameWebsite.SocialGameBLLService.User GetUser(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> GetUserAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetTotalNumberOfUsers", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetTotalNumberOfUsersResponse")]
        int GetTotalNumberOfUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetTotalNumberOfUsers", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetTotalNumberOfUsersResponse")]
        System.Threading.Tasks.Task<int> GetTotalNumberOfUsersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/UpdateUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/UpdateUserResponse")]
        SocialGameWebsite.SocialGameBLLService.User UpdateUser(SocialGameWebsite.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/UpdateUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/UpdateUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> UpdateUserAsync(SocialGameWebsite.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetHumourStatus", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetHumourStatusResponse")]
        SocialGameWebsite.SocialGameBLLService.HumourStatus GetHumourStatus(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetHumourStatus", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetHumourStatusResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.HumourStatus> GetHumourStatusAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetAllHumourStatus", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetAllHumourStatusResponse")]
        SocialGameWebsite.SocialGameBLLService.HumourStatus[] GetAllHumourStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetAllHumourStatus", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetAllHumourStatusResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.HumourStatus[]> GetAllHumourStatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTags", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagsResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipTag[] GetRelationshipTags();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTags", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipTag[]> GetRelationshipTagsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTag", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipTag GetRelationshipTag(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipTag", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipTagResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipTag> GetRelationshipTagAsync(int Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelatedUsers", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelatedUsersResponse")]
        SocialGameWebsite.SocialGameBLLService.User[] GetRelatedUsers(SocialGameWebsite.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelatedUsers", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelatedUsersResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetRelatedUsersAsync(SocialGameWebsite.SocialGameBLLService.User User);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipResponse")]
        SocialGameWebsite.SocialGameBLLService.Relationship GetRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Relationship> GetRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/CheckRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/CheckRelationshipResponse")]
        bool CheckRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/CheckRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/CheckRelationshipResponse")]
        System.Threading.Tasks.Task<bool> CheckRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/DeleteRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/DeleteRelationshipResponse")]
        void DeleteRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/DeleteRelationship", ReplyAction="http://tempuri.org/ISocialGameBLLService/DeleteRelationshipResponse")]
        System.Threading.Tasks.Task DeleteRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationships", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsResponse")]
        SocialGameWebsite.SocialGameBLLService.Graph GetRelationships(SocialGameWebsite.SocialGameBLLService.User User, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationships", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Graph> GetRelationshipsAsync(SocialGameWebsite.SocialGameBLLService.User User, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequestResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipRequest MakeRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other, int RelationshipTagId, int Strength);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/MakeRelationshipRequestResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest> MakeRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other, int RelationshipTagId, int Strength);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/AcceptRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/AcceptRelationshipRequestResponse")]
        void AcceptRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/AcceptRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/AcceptRelationshipRequestResponse")]
        System.Threading.Tasks.Task AcceptRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RejectRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/RejectRelationshipRequestResponse")]
        void RejectRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RejectRelationshipRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/RejectRelationshipRequestResponse")]
        System.Threading.Tasks.Task RejectRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserPendingRequests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserPendingRequestsResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipRequest[] GetUserPendingRequests(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserPendingRequests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserPendingRequestsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest[]> GetUserPendingRequestsAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPendingRequestsToUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPendingRequestsToUserResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipRequest[] GetPendingRequestsToUser(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPendingRequestsToUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPendingRequestsToUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest[]> GetPendingRequestsToUserAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPendingRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPendingRequestResponse")]
        SocialGameWebsite.SocialGameBLLService.RelationshipRequest GetPendingRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPendingRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPendingRequestResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest> GetPendingRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/CheckPendingRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/CheckPendingRequestResponse")]
        bool CheckPendingRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/CheckPendingRequest", ReplyAction="http://tempuri.org/ISocialGameBLLService/CheckPendingRequestResponse")]
        System.Threading.Tasks.Task<bool> CheckPendingRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetShortestPath", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetShortestPathResponse")]
        SocialGameWebsite.SocialGameBLLService.User[] GetShortestPath(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Goal, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetShortestPath", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetShortestPathResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetShortestPathAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Goal, int Depth);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserLevel", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserLevelResponse")]
        int GetUserLevel(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserLevel", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserLevelResponse")]
        System.Threading.Tasks.Task<int> GetUserLevelAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserPoints", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserPointsResponse")]
        float GetUserPoints(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserPoints", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserPointsResponse")]
        System.Threading.Tasks.Task<float> GetUserPointsAsync(string Email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/SetUserLevel", ReplyAction="http://tempuri.org/ISocialGameBLLService/SetUserLevelResponse")]
        void SetUserLevel(string Email, int Level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/SetUserLevel", ReplyAction="http://tempuri.org/ISocialGameBLLService/SetUserLevelResponse")]
        System.Threading.Tasks.Task SetUserLevelAsync(string Email, int Level);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/SetUserPoints", ReplyAction="http://tempuri.org/ISocialGameBLLService/SetUserPointsResponse")]
        void SetUserPoints(string Email, float Points);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/SetUserPoints", ReplyAction="http://tempuri.org/ISocialGameBLLService/SetUserPointsResponse")]
        System.Threading.Tasks.Task SetUserPointsAsync(string Email, float Points);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetFriendsWithCommonInterests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetFriendsWithCommonInterestsResponse")]
        SocialGameWebsite.SocialGameBLLService.User[] GetFriendsWithCommonInterests(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest[] Interests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetFriendsWithCommonInterests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetFriendsWithCommonInterestsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetFriendsWithCommonInterestsAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest[] Interests);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetGraphStats", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetGraphStatsResponse")]
        SocialGameWebsite.SocialGameBLLService.NetworkStatistics GetGraphStats(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetGraphStats", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetGraphStatsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.NetworkStatistics> GetGraphStatsAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPossibleFriends", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPossibleFriendsResponse")]
        SocialGameWebsite.SocialGameBLLService.User[] GetPossibleFriends(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPossibleFriends", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPossibleFriendsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetPossibleFriendsAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/AddInterestToUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/AddInterestToUserResponse")]
        SocialGameWebsite.SocialGameBLLService.Interest AddInterestToUser(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest, string Freebase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/AddInterestToUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/AddInterestToUserResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest> AddInterestToUserAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest, string Freebase);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RemoveInterestFromUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RemoveInterestFromUserResponse")]
        void RemoveInterestFromUser(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/RemoveInterestFromUser", ReplyAction="http://tempuri.org/ISocialGameBLLService/RemoveInterestFromUserResponse")]
        System.Threading.Tasks.Task RemoveInterestFromUserAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetInterest", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetInterestResponse")]
        SocialGameWebsite.SocialGameBLLService.Interest GetInterest(int InterestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetInterest", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetInterestResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest> GetInterestAsync(int InterestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserInterests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserInterestsResponse")]
        SocialGameWebsite.SocialGameBLLService.Interest[] GetUserInterests(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetUserInterests", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetUserInterestsResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest[]> GetUserInterestsAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetInterestsTagCloud", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetInterestsTagCloudResponse")]
        System.Collections.Generic.Dictionary<string, int> GetInterestsTagCloud(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetInterestsTagCloud", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetInterestsTagCloudResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetInterestsTagCloudAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipsTagCloud", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsTagCloudResponse")]
        System.Collections.Generic.Dictionary<string, int> GetRelationshipsTagCloud(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetRelationshipsTagCloud", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetRelationshipsTagCloudResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetRelationshipsTagCloudAsync(SocialGameWebsite.SocialGameBLLService.User Me);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPaginatedUsersScores", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPaginatedUsersScoresResponse")]
        SocialGameWebsite.SocialGameBLLService.UserScore[] GetPaginatedUsersScores(int ElementsPerPage, int PageNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISocialGameBLLService/GetPaginatedUsersScores", ReplyAction="http://tempuri.org/ISocialGameBLLService/GetPaginatedUsersScoresResponse")]
        System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.UserScore[]> GetPaginatedUsersScoresAsync(int ElementsPerPage, int PageNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface ISocialGameBLLServiceChannel : SocialGameWebsite.SocialGameBLLService.ISocialGameBLLService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class SocialGameBLLServiceClient : System.ServiceModel.ClientBase<SocialGameWebsite.SocialGameBLLService.ISocialGameBLLService>, SocialGameWebsite.SocialGameBLLService.ISocialGameBLLService {
        
        public SocialGameBLLServiceClient() {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialGameBLLServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SocialGameBLLServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public SocialGameWebsite.SocialGameBLLService.CompositeType GetDataUsingDataContract(SocialGameWebsite.SocialGameBLLService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.CompositeType> GetDataUsingDataContractAsync(SocialGameWebsite.SocialGameBLLService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User RegisterUser(string Email, string Password) {
            return base.Channel.RegisterUser(Email, Password);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> RegisterUserAsync(string Email, string Password) {
            return base.Channel.RegisterUserAsync(Email, Password);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User LoginUser(string Email, string Password) {
            return base.Channel.LoginUser(Email, Password);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> LoginUserAsync(string Email, string Password) {
            return base.Channel.LoginUserAsync(Email, Password);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User GetUser(string Email) {
            return base.Channel.GetUser(Email);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> GetUserAsync(string Email) {
            return base.Channel.GetUserAsync(Email);
        }
        
        public int GetTotalNumberOfUsers() {
            return base.Channel.GetTotalNumberOfUsers();
        }
        
        public System.Threading.Tasks.Task<int> GetTotalNumberOfUsersAsync() {
            return base.Channel.GetTotalNumberOfUsersAsync();
        }
        
        public SocialGameWebsite.SocialGameBLLService.User UpdateUser(SocialGameWebsite.SocialGameBLLService.User User) {
            return base.Channel.UpdateUser(User);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User> UpdateUserAsync(SocialGameWebsite.SocialGameBLLService.User User) {
            return base.Channel.UpdateUserAsync(User);
        }
        
        public SocialGameWebsite.SocialGameBLLService.HumourStatus GetHumourStatus(int Id) {
            return base.Channel.GetHumourStatus(Id);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.HumourStatus> GetHumourStatusAsync(int Id) {
            return base.Channel.GetHumourStatusAsync(Id);
        }
        
        public SocialGameWebsite.SocialGameBLLService.HumourStatus[] GetAllHumourStatus() {
            return base.Channel.GetAllHumourStatus();
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.HumourStatus[]> GetAllHumourStatusAsync() {
            return base.Channel.GetAllHumourStatusAsync();
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipTag[] GetRelationshipTags() {
            return base.Channel.GetRelationshipTags();
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipTag[]> GetRelationshipTagsAsync() {
            return base.Channel.GetRelationshipTagsAsync();
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipTag GetRelationshipTag(int Id) {
            return base.Channel.GetRelationshipTag(Id);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipTag> GetRelationshipTagAsync(int Id) {
            return base.Channel.GetRelationshipTagAsync(Id);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User[] GetRelatedUsers(SocialGameWebsite.SocialGameBLLService.User User) {
            return base.Channel.GetRelatedUsers(User);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetRelatedUsersAsync(SocialGameWebsite.SocialGameBLLService.User User) {
            return base.Channel.GetRelatedUsersAsync(User);
        }
        
        public SocialGameWebsite.SocialGameBLLService.Relationship GetRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.GetRelationship(Me, Other);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Relationship> GetRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.GetRelationshipAsync(Me, Other);
        }
        
        public bool CheckRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.CheckRelationship(Me, Other);
        }
        
        public System.Threading.Tasks.Task<bool> CheckRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.CheckRelationshipAsync(Me, Other);
        }
        
        public void DeleteRelationship(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            base.Channel.DeleteRelationship(Me, Other);
        }
        
        public System.Threading.Tasks.Task DeleteRelationshipAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.DeleteRelationshipAsync(Me, Other);
        }
        
        public SocialGameWebsite.SocialGameBLLService.Graph GetRelationships(SocialGameWebsite.SocialGameBLLService.User User, int Depth) {
            return base.Channel.GetRelationships(User, Depth);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Graph> GetRelationshipsAsync(SocialGameWebsite.SocialGameBLLService.User User, int Depth) {
            return base.Channel.GetRelationshipsAsync(User, Depth);
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipRequest MakeRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other, int RelationshipTagId, int Strength) {
            return base.Channel.MakeRelationshipRequest(Me, Other, RelationshipTagId, Strength);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest> MakeRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other, int RelationshipTagId, int Strength) {
            return base.Channel.MakeRelationshipRequestAsync(Me, Other, RelationshipTagId, Strength);
        }
        
        public void AcceptRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            base.Channel.AcceptRelationshipRequest(Me, Other);
        }
        
        public System.Threading.Tasks.Task AcceptRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.AcceptRelationshipRequestAsync(Me, Other);
        }
        
        public void RejectRelationshipRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            base.Channel.RejectRelationshipRequest(Me, Other);
        }
        
        public System.Threading.Tasks.Task RejectRelationshipRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.RejectRelationshipRequestAsync(Me, Other);
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipRequest[] GetUserPendingRequests(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetUserPendingRequests(Me);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest[]> GetUserPendingRequestsAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetUserPendingRequestsAsync(Me);
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipRequest[] GetPendingRequestsToUser(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetPendingRequestsToUser(Me);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest[]> GetPendingRequestsToUserAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetPendingRequestsToUserAsync(Me);
        }
        
        public SocialGameWebsite.SocialGameBLLService.RelationshipRequest GetPendingRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.GetPendingRequest(Me, Other);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.RelationshipRequest> GetPendingRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.GetPendingRequestAsync(Me, Other);
        }
        
        public bool CheckPendingRequest(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.CheckPendingRequest(Me, Other);
        }
        
        public System.Threading.Tasks.Task<bool> CheckPendingRequestAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Other) {
            return base.Channel.CheckPendingRequestAsync(Me, Other);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User[] GetShortestPath(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Goal, int Depth) {
            return base.Channel.GetShortestPath(Me, Goal, Depth);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetShortestPathAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.User Goal, int Depth) {
            return base.Channel.GetShortestPathAsync(Me, Goal, Depth);
        }
        
        public int GetUserLevel(string Email) {
            return base.Channel.GetUserLevel(Email);
        }
        
        public System.Threading.Tasks.Task<int> GetUserLevelAsync(string Email) {
            return base.Channel.GetUserLevelAsync(Email);
        }
        
        public float GetUserPoints(string Email) {
            return base.Channel.GetUserPoints(Email);
        }
        
        public System.Threading.Tasks.Task<float> GetUserPointsAsync(string Email) {
            return base.Channel.GetUserPointsAsync(Email);
        }
        
        public void SetUserLevel(string Email, int Level) {
            base.Channel.SetUserLevel(Email, Level);
        }
        
        public System.Threading.Tasks.Task SetUserLevelAsync(string Email, int Level) {
            return base.Channel.SetUserLevelAsync(Email, Level);
        }
        
        public void SetUserPoints(string Email, float Points) {
            base.Channel.SetUserPoints(Email, Points);
        }
        
        public System.Threading.Tasks.Task SetUserPointsAsync(string Email, float Points) {
            return base.Channel.SetUserPointsAsync(Email, Points);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User[] GetFriendsWithCommonInterests(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest[] Interests) {
            return base.Channel.GetFriendsWithCommonInterests(Me, Interests);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetFriendsWithCommonInterestsAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest[] Interests) {
            return base.Channel.GetFriendsWithCommonInterestsAsync(Me, Interests);
        }
        
        public SocialGameWebsite.SocialGameBLLService.NetworkStatistics GetGraphStats(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetGraphStats(Me);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.NetworkStatistics> GetGraphStatsAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetGraphStatsAsync(Me);
        }
        
        public SocialGameWebsite.SocialGameBLLService.User[] GetPossibleFriends(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetPossibleFriends(Me);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.User[]> GetPossibleFriendsAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetPossibleFriendsAsync(Me);
        }
        
        public SocialGameWebsite.SocialGameBLLService.Interest AddInterestToUser(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest, string Freebase) {
            return base.Channel.AddInterestToUser(Me, Interest, Freebase);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest> AddInterestToUserAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest, string Freebase) {
            return base.Channel.AddInterestToUserAsync(Me, Interest, Freebase);
        }
        
        public void RemoveInterestFromUser(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest) {
            base.Channel.RemoveInterestFromUser(Me, Interest);
        }
        
        public System.Threading.Tasks.Task RemoveInterestFromUserAsync(SocialGameWebsite.SocialGameBLLService.User Me, SocialGameWebsite.SocialGameBLLService.Interest Interest) {
            return base.Channel.RemoveInterestFromUserAsync(Me, Interest);
        }
        
        public SocialGameWebsite.SocialGameBLLService.Interest GetInterest(int InterestID) {
            return base.Channel.GetInterest(InterestID);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest> GetInterestAsync(int InterestID) {
            return base.Channel.GetInterestAsync(InterestID);
        }
        
        public SocialGameWebsite.SocialGameBLLService.Interest[] GetUserInterests(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetUserInterests(Me);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.Interest[]> GetUserInterestsAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetUserInterestsAsync(Me);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetInterestsTagCloud(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetInterestsTagCloud(Me);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetInterestsTagCloudAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetInterestsTagCloudAsync(Me);
        }
        
        public System.Collections.Generic.Dictionary<string, int> GetRelationshipsTagCloud(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetRelationshipsTagCloud(Me);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> GetRelationshipsTagCloudAsync(SocialGameWebsite.SocialGameBLLService.User Me) {
            return base.Channel.GetRelationshipsTagCloudAsync(Me);
        }
        
        public SocialGameWebsite.SocialGameBLLService.UserScore[] GetPaginatedUsersScores(int ElementsPerPage, int PageNumber) {
            return base.Channel.GetPaginatedUsersScores(ElementsPerPage, PageNumber);
        }
        
        public System.Threading.Tasks.Task<SocialGameWebsite.SocialGameBLLService.UserScore[]> GetPaginatedUsersScoresAsync(int ElementsPerPage, int PageNumber) {
            return base.Channel.GetPaginatedUsersScoresAsync(ElementsPerPage, PageNumber);
        }
    }
}
